dbim_checklist = {
    1: "Select only one colour palette consisting of 1 key colour with its 5 gradients",
    2: "Select a colour that best represents your Government entity",
    3: "All iconography used in the platform must be of the selected colour palette only",
    4: "Footer must be the darkest tone of the colour palette",
    5: "Call to actions buttons must be of the chosen colour palette",
    6: "Highlight backgrounds must be either in linen or from the chosen colour palette",
    7: "In case of a well-established brand colour for any government entity select a palette that is closest to the established brand colours",
    8: "The colour chosen must be used for digital purposes only",
    9: "All text must be in deep earthy brown (#150202)",
    10: "All logo lockups must be in black (#000000)",
    11: "All primary backgrounds to be in Inclusive white (#FFFFFF)",
    12: "The State Emblem used is in inclusive white on dark background OR in Black on white background",
    13: "Use the icons from the icon library provided in the Digital Brand Experience Toolkit website under the Visual Library section",
    14: "Use icons from the same style as defined in Section 3.1",
    15: "Icons scale must be as per the sizes provided - 24x24, 32x32, 48x48 or 64x64",
    16: "Don’t use icons styles such as outlined and filled together, only use one consistent style",
    17: "Using icons on images - place a black overlay with 80% opacity over an image before placing a contrasting colour icon",
    18: "Contextual icons curated from the internet match the style established in the DBIM",
    19: "Icon proportions are retained as per the original design",
    20: "All text used is in Noto Sans",
    21: "Text used in headings; body text & image caption are left aligned",
    22: "Text used in column grid is justified",
    23: "Character kerning is set to metric",
    24: "Type scale for websites is as defined in DBIM Section 4.3.1",
    25: "Type scale for apps & webapps is as defined in DBIM Section 4.3.2",
    26: "Type colour used is as per DBIM Section 4.5",
    27: "Logo lockup must be chosen from DBIM Section 5.2 based on the type of Government entity",
    28: "Generic header component must be chosen from DBIM Section 5.4",
    29: "All the subcomponents of the generic header component must be enabled and accessible",
    30: "Footer component must contain all the key information sets mentioned in DBIM Section 5.5",
    31: "Footer must state the appropriate lineage as per the type of Government entity",
    32: "Background images are maximum up to 2 MB",
    33: "Banner and header images are maximum up to 2MB",
    34: "Thumbnail images are maximum up to 100 KB",
    35: "All images are in JPEG, PNG or WEBP format only",
    36: "High resolution images are maximum up to 5 MB",
    37: "Alternative text is provided for all images",
    38: "Alternative text is maximum up to 100 characters",
    39: "Stock imagery curated from the internet has necessary permissions and licenses",
    40: "Images used do not have watermarks",
    41: "Headshot images for individuals used on the website is as per the proportions defined in Section 6.1.4",
    42: "Tone of voice follows the principles as per Section 7.2.1",
    43: "Dedicated space is provided for CIPS content on the homepage as per Section 7.5",
    44: "Content grouping is done as per Section 7.1",
    45: "Minimal content as per Section 7.1",
    54: "Server Response time is minimized",
    55: "Browser caching is enabled",
    56: "Images are optimized",
    57: "JavaScript execution is optimized",
    58: "Browser pre-loading techniques are used",
    59: "The loading='lazy' attribute is used for images and lazy loading for off-screen media",
    60: "Resource loading order optimized",
    61: "Critical resources are minimized and prioritized",
    62: "Asynchronous loading used for non-essential scripts",
    63: "Website is tested for responsiveness across multiple screen sizes",
    64: "Content Delivery Network (CDN) implemented to cache and deliver static assets",
    65: "Appropriate cache headers set for static assets",
    66: "Icons for voice and image-based inputs are provided as per DBIM",
    67: "Text based inputs in English are tested for accurate search results",
    68: "Text based inputs in regional languages are tested for accurate search results",
    69: "Voice input in English is tested for speech-to-text input accuracy",
    70: "Voice input in regional languages is tested for speech-to-text input accuracy",
    71: "Search result language is the same as search input language",
    72: "Voice based search results are accompanied by text-to-speech output"
}
